services:
  web:
#    image: bennerlukas/libcap_web:libcap
    build: src/LibCap/WebFrontend/.
    ports:
      - "5000:5000"
    depends_on:
      - database
      - memcached
    restart: on-failure

  database:
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
    image: 'postgres:14.1'
    restart: always
    volumes:
      - ./src/LibCap/Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  memcached:
    image: 'memcached'
    ports:
      - '11211:11211'
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - database

  mosquitto:
    image: 'toke/mosquitto'
    ports:
      - '1883:1883'
      - '9001:9001'
    restart: always

  backend:
#    image: bennerlukas/libcap_backend:libcap
    build: src/LibCap/Backend/.
    depends_on:
      - mosquitto
      - database

